Documentación.
VeronicaMujica/MiniProyecto1 pull request #7
Opened 2024-04-03 22:25 UTC by Sebastian-Ceron-Orozco

Termine de hacer la documentación que creo necesaria, si hay algo que no sea correcto, me avisan y lo cambiare.

2024-04-03 22:41 UTC, JeidyMurillo commented
Hola, debes verificar nuevamente la documentación debido a la ortografía y hay algunas palabras que le faltan la tilde.

2024-04-03 22:47 UTC, VeronicaMujica reviewed
Si, sería ideal corregir la ortografía. De resto todo perfecto.

2024-04-03 23:11 UTC, JeidyMurillo requested changes

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/App.java
> +        while (true) { // Creacion del menu inicial donde se encontraran todas las opciones con sus respectivas funciones asignadas.
Creación del menú inicial donde se encontrarán todas las opciones con sus respectivas funciones asignadas.

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/App.java
> +    public static void main(String[] args) { // Funcion principal o main, hace que la aplicación funcione de forma ordenada.
Función principal o main, hace que la aplicación funcione de forma ordenada.

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/App.java
> +            switch (opcion) { // Apartado de seleccion, donde se encuentran todas las posibles selecciones dentro de la aplicacion y sus dialogos preescritos.
Apartado de selección, donde se encuentran todas las posibles selecciones dentro de la aplicación y sus diálogos pre escritos.

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/Cliente/CRUDClientes.java
> +public class CRUDClientes { // Este es la clase que abarca toda la funcionalidad de la aplicacion como sus funciones y el vector clientes.
aplicación

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/Cliente/CRUDClientes.java
> +    private static ArrayList<Clientes> clientes; // Creacion de un vector.
Creación de un vector.

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/Cliente/CRUDClientes.java
> +    public CRUDClientes() { // Funcion de crear un nuevo vector para los clientes cliente.
Función

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/Cliente/CRUDClientes.java
> +    public void crearCliente(Clientes cliente) { // Funcion crear cliente.
Función

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/Cliente/CRUDClientes.java
> +    public static Clientes buscarCedula(long cedula) { // Funcion para buscar cliente por cedula.
Función para buscar cliente por cédula.

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/Cliente/CRUDClientes.java
> +    public void insertarDinero(long cedula, double cantidadDinero) { // Funcion para insertar mas dinero a la cuenta del cliente.
Función para insertar más dinero a la cuenta del cliente.

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/Cliente/CRUDClientes.java
> +    public void actualizarDinero(long cedula, double cantidadDinero) { // Funcion para actualizar el dinero del cliente.
Función

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/Cliente/CRUDClientes.java
> +    public void eliminarDinero(long cedula, double cantidadDinero) { // Funcion para eliminar dinero de la cuenta del cliente.
Función

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/Cliente/CRUDClientes.java
> +    public void buscarCliente(String nombre) { // Funcion para buscar a un cliente por su nombre.
Función

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/Cliente/CRUDClientes.java
> +    public void listarClientes() { // Funcion para listar todos los clientes.
Función

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/Cliente/CRUDClientes.java
> +    public void SolicitudPrestamo(long cedula) { // Funcion para solicitar un prestamo.
Función para solicitar un préstamo.

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/Cliente/CRUDClientes.java
> +        public static void solicitudCdt(long cedula) { // Funcion para solicitar un Cdt.
Función para solicitar un CDT.

2024-04-03 23:11 UTC, JeidyMurillo commented on MiniProyecto1/src/Cliente/Clientes.java
> +public class Clientes { // Creacion de la clase cliente con sus respectivos atributos.
Creación

2024-04-04 03:53 UTC, VeronicaMujica approved these changes

2024-04-04 03:54 UTC, JeidyMurillo approved these changes
Hola, listo.

2024-04-04 03:58 UTC, merged